# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_SUNXI) += sun55i-t527-avaota-a1.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun55i-t527-longanpi-4b-pcie.dtb
dtb-$(CONFIG_ARCH_SUNXI) += sun55i-t527-longanpi-4b-usb3.dtb
